import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import type { SleepLogView, WeightLogView } from "../../src/domain";
import { useApp } from "../../src/state/AppProvider";
import { colors, shared } from "../../src/ui/styles";
import { isoToday, numeric } from "../../src/utils/date";

type Quality = "poor" | "average" | "good";
export default function WellnessScreen() {
  const { adapter, t } = useApp();
  const [date, setDate] = useState(isoToday()); const [sleep, setSleep] = useState<SleepLogView | null>(null); const [weight, setWeight] = useState<WeightLogView | null>(null);
  const [hours, setHours] = useState(""); const [quality, setQuality] = useState<Quality>("average"); const [weightKg, setWeightKg] = useState(""); const [notes, setNotes] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { setBusy(true); try { const [nextSleep, nextWeight] = await Promise.all([adapter.getSleep(date), adapter.getWeight(date)]); setSleep(nextSleep); setWeight(nextWeight); setHours(nextSleep ? String(nextSleep.hours) : ""); setQuality(nextSleep?.quality ?? "average"); setWeightKg(nextWeight ? String(nextWeight.weightKg) : ""); setNotes(nextSleep?.notes ?? nextWeight?.notes ?? ""); } catch (error) { setMessage(error instanceof Error ? error.message : t("common.error")); } finally { setBusy(false); } }, [adapter, date, t]);
  useEffect(() => { void load(); }, [load]);
  async function saveSleep() { const value = numeric(hours); if (value == null) { setMessage("Enter sleep hours."); return; } setBusy(true); try { const next = await adapter.saveSleep({ date, hours: value, quality, notes: notes || null }); setSleep(next); } catch (error) { setMessage(error instanceof Error ? error.message : t("common.error")); } finally { setBusy(false); } }
  async function saveWeight() { const value = numeric(weightKg); if (value == null) { setMessage("Enter a weight."); return; } setBusy(true); try { const next = await adapter.saveWeight({ date, weightKg: value, notes: notes || null }); setWeight(next); } catch (error) { setMessage(error instanceof Error ? error.message : t("common.error")); } finally { setBusy(false); } }
  return <SafeAreaView style={shared.page} edges={["left", "right"]}><ScrollView contentContainerStyle={shared.content} keyboardShouldPersistTaps="handled"><View style={shared.header}><Text style={shared.title}>{t("wellness.title")}</Text><Text style={shared.subtitle}>{t("dashboard.subtitle")}</Text></View>{message ? <Text style={shared.error}>{message}</Text> : null}<View style={shared.panel}><Text style={shared.label}>{t("common.date")}</Text><TextInput value={date} onChangeText={setDate} style={shared.input} placeholder="YYYY-MM-DD" /></View><View style={shared.panel}><Text style={shared.sectionTitle}>{t("wellness.sleepDuration")}</Text><TextInput value={hours} onChangeText={setHours} style={shared.input} keyboardType="numeric" placeholder={t("wellness.sleepDuration")} /><Text style={shared.label}>{t("wellness.sleepQuality")}</Text><View style={{ flexDirection: "row", gap: 8 }}>{(["poor", "average", "good"] as Quality[]).map((item) => <Pressable key={item} style={[shared.secondaryButton, quality === item && { backgroundColor: colors.mint }]} onPress={() => setQuality(item)}><Text style={shared.secondaryButtonText}>{t(`wellness.${item}`)}</Text></Pressable>)}</View><TextInput value={notes} onChangeText={setNotes} style={shared.input} placeholder={t("common.notes")} /><Pressable disabled={busy} style={shared.primaryButton} onPress={() => void saveSleep()}>{busy ? <ActivityIndicator color="white" /> : <Text style={shared.primaryButtonText}>{t("common.save")}</Text>}</Pressable>{sleep ? <Pressable disabled={busy} onPress={() => void adapter.deleteSleep(date).then(() => setSleep(null))}><Text style={{ color: colors.danger, fontWeight: "700" }}>{t("common.delete")}</Text></Pressable> : null}</View><View style={shared.panel}><Text style={shared.sectionTitle}>{t("wellness.weightKg")}</Text><TextInput value={weightKg} onChangeText={setWeightKg} style={shared.input} keyboardType="numeric" placeholder={t("wellness.weightKg")} /><Pressable disabled={busy} style={shared.primaryButton} onPress={() => void saveWeight()}><Text style={shared.primaryButtonText}>{t("common.save")}</Text></Pressable>{weight ? <Pressable disabled={busy} onPress={() => void adapter.deleteWeight(date).then(() => setWeight(null))}><Text style={{ color: colors.danger, fontWeight: "700" }}>{t("common.delete")}</Text></Pressable> : null}</View></ScrollView></SafeAreaView>;
}
